export type WorkflowStatus = "idea" | "developing" | "draft" | "review" | "approved" | "ready_to_share" | "archived";

export const platforms = ["Instagram", "Facebook", "X", "TikTok"] as const;
export const themes = ["Questions", "Testimonies", "Invitations", "Countdown"] as const;

export const ideas = [
  { id: "why-church", title: "Why would I go back to church?", description: "A candid invitation for someone who may believe in God but has lost trust in churches.", theme: "Questions", owner: "Bridge Team", status: "review" as WorkflowStatus, platforms: ["Instagram", "Facebook", "TikTok"], updated: "Today" },
  { id: "suffering", title: "Why does God allow suffering?", description: "Make room for the question without pretending there is a quick or painless answer, then invite people to explore it in community.", theme: "Questions", owner: "Bridge Team", status: "review" as WorkflowStatus, platforms: ["Instagram", "Facebook", "X"], updated: "Today" },
  { id: "dinner", title: "Dinner with no strings attached", description: "An invitation centered on a shared meal, free childcare, honest conversation, and no pressure to have Christianity figured out.", theme: "Invitations", owner: "Bridge Team", status: "review" as WorkflowStatus, platforms: ["Instagram", "Facebook"], updated: "Today" },
  { id: "story", title: "I brought my doubts with me", description: "A short first-person testimony about arriving skeptical and finding room for honest questions about Jesus.", theme: "Testimonies", owner: "Bridge Team", status: "review" as WorkflowStatus, platforms: ["Instagram", "Facebook", "TikTok"], updated: "Today" },
  { id: "who-is-jesus", title: "Who did Jesus actually claim to be?", description: "A question-led post that invites people to look beyond assumptions and examine Jesus' own words and claims.", theme: "Questions", owner: "Bridge Team", status: "review" as WorkflowStatus, platforms: ["Instagram", "Facebook", "X", "TikTok"], updated: "Today" },
  { id: "too-late", title: "Is it too late for me to come back to God?", description: "Speak to people who feel ashamed, distant, or disqualified and point toward the grace offered in Christ.", theme: "Questions", owner: "Bridge Team", status: "review" as WorkflowStatus, platforms: ["Instagram", "Facebook", "TikTok"], updated: "Today" },
  { id: "ordinary-people", title: "Bridge is for ordinary people with real questions", description: "A simple invitation that lowers the barrier for people who assume a church course is only for people who already know the Bible.", theme: "Invitations", owner: "Bridge Team", status: "review" as WorkflowStatus, platforms: ["Instagram", "Facebook"], updated: "Today" },
  { id: "changed-mind", title: "I expected a sales pitch. I found conversation.", description: "A testimony-style post describing the surprise of finding a relaxed place to ask questions rather than being pressured into an answer.", theme: "Testimonies", owner: "Bridge Team", status: "review" as WorkflowStatus, platforms: ["Instagram", "Facebook", "TikTok"], updated: "Today" },
  { id: "one-week", title: "One week until Bridge begins", description: "A countdown post with the September 9 start date, free dinner and childcare, and a clear invitation to register or simply come.", theme: "Countdown", owner: "Bridge Team", status: "review" as WorkflowStatus, platforms: ["Instagram", "Facebook", "X"], updated: "Today" },
  { id: "bring-the-one", title: "Who is your one?", description: "Encourage church members to think of one person they can personally invite to Bridge rather than treating outreach as a general announcement.", theme: "Invitations", owner: "Bridge Team", status: "review" as WorkflowStatus, platforms: ["Instagram", "Facebook"], updated: "Today" },
];

export const shareItems = [
  { id: "suffering-video", title: "Why does God allow suffering?", type: "Video", duration: "27-second video", theme: "Questions", campaign: "Bridge Fall 2026", platforms: ["Instagram", "Facebook", "TikTok"], caption: "If God is good, why is there so much suffering? That question deserves more than a slogan. Bridge is a place to bring honest questions, share a meal, and explore Christianity without pressure.", accent: "from-[#214e3d] to-[#6e8f76]" },
  { id: "doubts-story", title: "You don't have to leave your questions at the door", type: "Image", duration: "Shareable image", theme: "Testimonies", campaign: "Bridge Fall 2026", platforms: ["Instagram", "Facebook", "X"], caption: "Questions and doubts are welcome at Bridge. Join us for ten relaxed evenings, a free dinner, and an honest exploration of Christianity.", accent: "from-[#9b6335] to-[#d7aa6a]" },
  { id: "free-dinner", title: "Dinner, childcare, and space to explore", type: "Invitation", duration: "Invitation card", theme: "Invitations", campaign: "Bridge Fall 2026", platforms: ["Instagram", "Facebook"], caption: "Curious about Christianity? Bridge begins September 9 in Malvern. Dinner and childcare are free, and there is no pressure. Come as you are.", accent: "from-[#593f57] to-[#b2869d]" },
];
