-- Bridge Media Hub V2: idea development, packages, approval, and public sharing.
create type public.app_role as enum ('contributor', 'media_team', 'approver', 'admin');
create type public.workflow_status as enum ('idea', 'developing', 'draft', 'review', 'approved', 'ready_to_share', 'archived');
create type public.share_event_type as enum ('view', 'caption_copy', 'media_download', 'share');

drop table if exists public.results cascade;
drop table if exists public.assignments cascade;
drop table if exists public.media_assets cascade;
drop table if exists public.content_platforms cascade;
drop table if exists public.content_items cascade;
drop type if exists public.content_status;

alter table public.campaigns add column if not exists is_active boolean not null default true;

create table public.user_roles (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role public.app_role not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (organization_id, profile_id, role)
);

create table public.campaign_themes (
  id uuid primary key default extensions.gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  parent_id uuid references public.campaign_themes(id) on delete set null,
  name text not null check (length(trim(name)) between 1 and 120),
  description text not null default '',
  sort_order smallint not null default 0,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (campaign_id, name)
);

create table public.content_types (
  id smallint generated by default as identity primary key,
  key text not null unique check (key ~ '^[a-z0-9_]+$'),
  name text not null unique,
  is_active boolean not null default true,
  sort_order smallint not null unique
);

create table public.ideas (
  id uuid primary key default extensions.gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  theme_id uuid references public.campaign_themes(id) on delete set null,
  title text not null check (length(trim(title)) between 1 and 200),
  description text not null check (length(trim(description)) > 0),
  notes text not null default '',
  status public.workflow_status not null default 'idea',
  owner_id uuid references public.profiles(id) on delete set null,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ideas_status_valid check (status in ('idea', 'developing', 'draft', 'archived'))
);

create table public.idea_platforms (
  idea_id uuid not null references public.ideas(id) on delete cascade,
  platform_id smallint not null references public.platforms(id) on delete restrict,
  primary key (idea_id, platform_id)
);

create table public.content_packages (
  id uuid primary key default extensions.gen_random_uuid(),
  idea_id uuid not null references public.ideas(id) on delete cascade,
  title text not null check (length(trim(title)) between 1 and 200),
  description text not null default '',
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.content_items (
  id uuid primary key default extensions.gen_random_uuid(),
  package_id uuid not null references public.content_packages(id) on delete cascade,
  content_type_id smallint not null references public.content_types(id) on delete restrict,
  theme_id uuid references public.campaign_themes(id) on delete set null,
  title text not null check (length(trim(title)) between 1 and 200),
  body text not null default '',
  caption text not null default '',
  call_to_action text not null default '',
  status public.workflow_status not null default 'draft',
  created_by uuid not null references public.profiles(id) on delete restrict,
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz,
  ready_at timestamptz,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint content_item_status_valid check (status in ('draft','review','approved','ready_to_share','archived')),
  constraint approval_fields_valid check (status not in ('approved','ready_to_share') or (approved_by is not null and approved_at is not null)),
  constraint ready_fields_valid check (status <> 'ready_to_share' or ready_at is not null)
);

create table public.content_platforms (
  content_item_id uuid not null references public.content_items(id) on delete cascade,
  platform_id smallint not null references public.platforms(id) on delete restrict,
  platform_caption text not null default '',
  primary key (content_item_id, platform_id)
);

create table public.media_assets (
  id uuid primary key default extensions.gen_random_uuid(),
  content_item_id uuid not null references public.content_items(id) on delete cascade,
  storage_path text not null unique check (storage_path !~ '(^|/)\.\.?(/|$)'),
  file_name text not null check (length(trim(file_name)) between 1 and 255),
  media_type text not null check (media_type in ('image','video','thumbnail')),
  mime_type text not null,
  width integer check (width is null or width > 0),
  height integer check (height is null or height > 0),
  duration_seconds numeric(10,2) check (duration_seconds is null or duration_seconds >= 0),
  size_bytes bigint not null check (size_bytes > 0),
  alt_text text not null default '',
  uploaded_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table public.assignments (
  id uuid primary key default extensions.gen_random_uuid(),
  content_item_id uuid not null references public.content_items(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete restrict,
  assigned_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique (content_item_id, profile_id)
);

create table public.review_comments (
  id uuid primary key default extensions.gen_random_uuid(),
  content_item_id uuid not null references public.content_items(id) on delete cascade,
  body text not null check (length(trim(body)) between 1 and 4000),
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.status_history (
  id uuid primary key default extensions.gen_random_uuid(),
  idea_id uuid references public.ideas(id) on delete cascade,
  content_item_id uuid references public.content_items(id) on delete cascade,
  from_status public.workflow_status,
  to_status public.workflow_status not null,
  note text not null default '',
  changed_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint exactly_one_history_target check ((idea_id is not null)::int + (content_item_id is not null)::int = 1)
);

create table public.share_events (
  id uuid primary key default extensions.gen_random_uuid(),
  content_item_id uuid not null references public.content_items(id) on delete cascade,
  event_type public.share_event_type not null,
  platform_id smallint references public.platforms(id) on delete set null,
  session_hash text,
  user_agent_family text,
  created_at timestamptz not null default now()
);

create index ideas_campaign_status_idx on public.ideas(campaign_id, status, updated_at desc);
create index content_items_package_status_idx on public.content_items(package_id, status, updated_at desc);
create index review_comments_item_idx on public.review_comments(content_item_id, created_at);
create index status_history_item_idx on public.status_history(content_item_id, created_at desc) where content_item_id is not null;
create index share_events_item_created_idx on public.share_events(content_item_id, created_at desc);

create trigger campaign_themes_set_updated_at before update on public.campaign_themes for each row execute function public.set_updated_at();
create trigger ideas_set_updated_at before update on public.ideas for each row execute function public.set_updated_at();
create trigger content_packages_set_updated_at before update on public.content_packages for each row execute function public.set_updated_at();
create trigger content_items_set_updated_at before update on public.content_items for each row execute function public.set_updated_at();
create trigger review_comments_set_updated_at before update on public.review_comments for each row execute function public.set_updated_at();

create function public.idea_organization(target_id uuid) returns uuid language sql stable security definer set search_path = '' as $$
  select c.organization_id from public.ideas i join public.campaigns c on c.id = i.campaign_id where i.id = target_id
$$;
create function public.item_organization(target_id uuid) returns uuid language sql stable security definer set search_path = '' as $$
  select c.organization_id from public.content_items ci join public.content_packages cp on cp.id = ci.package_id join public.ideas i on i.id = cp.idea_id join public.campaigns c on c.id = i.campaign_id where ci.id = target_id
$$;
create function public.has_app_role(target_org uuid, allowed public.app_role[]) returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.user_roles r where r.organization_id = target_org and r.profile_id = (select auth.uid()) and r.role = any(allowed))
$$;

revoke all on function public.idea_organization(uuid), public.item_organization(uuid), public.has_app_role(uuid, public.app_role[]) from public, anon;
grant execute on function public.idea_organization(uuid), public.item_organization(uuid), public.has_app_role(uuid, public.app_role[]) to authenticated;
grant execute on function public.item_organization(uuid) to anon;

alter table public.user_roles enable row level security;
alter table public.campaign_themes enable row level security;
alter table public.content_types enable row level security;
alter table public.ideas enable row level security;
alter table public.idea_platforms enable row level security;
alter table public.content_packages enable row level security;
alter table public.content_items enable row level security;
alter table public.content_platforms enable row level security;
alter table public.media_assets enable row level security;
alter table public.assignments enable row level security;
alter table public.review_comments enable row level security;
alter table public.status_history enable row level security;
alter table public.share_events enable row level security;

create policy user_roles_member_read on public.user_roles for select to authenticated using (public.is_organization_member(organization_id));
create policy user_roles_admin_write on public.user_roles for all to authenticated using (public.has_app_role(organization_id, array['admin']::public.app_role[])) with check (public.has_app_role(organization_id, array['admin']::public.app_role[]));
create policy themes_member_read on public.campaign_themes for select to authenticated using (public.is_organization_member(public.campaign_organization(campaign_id)));
create policy themes_admin_write on public.campaign_themes for all to authenticated using (public.has_app_role(public.campaign_organization(campaign_id), array['admin']::public.app_role[])) with check (public.has_app_role(public.campaign_organization(campaign_id), array['admin']::public.app_role[]));
create policy types_public_read on public.content_types for select to anon, authenticated using (is_active);
create policy platforms_public_read on public.platforms for select to anon using (is_active);
create policy ideas_member_read on public.ideas for select to authenticated using (public.is_organization_member(public.campaign_organization(campaign_id)));
create policy ideas_contributor_insert on public.ideas for insert to authenticated with check (created_by = (select auth.uid()) and public.has_app_role(public.campaign_organization(campaign_id), array['contributor','media_team','approver','admin']::public.app_role[]));
create policy ideas_owner_update on public.ideas for update to authenticated using (created_by = (select auth.uid()) or public.has_app_role(public.campaign_organization(campaign_id), array['media_team','approver','admin']::public.app_role[])) with check (public.is_organization_member(public.campaign_organization(campaign_id)));
create policy idea_platforms_member_all on public.idea_platforms for all to authenticated using (public.is_organization_member(public.idea_organization(idea_id))) with check (public.is_organization_member(public.idea_organization(idea_id)));
create policy packages_member_all on public.content_packages for all to authenticated using (public.is_organization_member(public.idea_organization(idea_id))) with check (public.has_app_role(public.idea_organization(idea_id), array['media_team','approver','admin']::public.app_role[]));
create policy items_member_read on public.content_items for select to authenticated using (public.is_organization_member(public.item_organization(id)));
create policy items_public_ready on public.content_items for select to anon using (status = 'ready_to_share');
create policy items_team_write on public.content_items for all to authenticated using (public.has_app_role(public.item_organization(id), array['media_team','approver','admin']::public.app_role[])) with check (public.has_app_role(public.item_organization(id), array['media_team','approver','admin']::public.app_role[]));
create policy content_platforms_public_ready on public.content_platforms for select to anon using (exists(select 1 from public.content_items i where i.id = content_item_id and i.status = 'ready_to_share'));
create policy content_platforms_member_all on public.content_platforms for all to authenticated using (public.is_organization_member(public.item_organization(content_item_id))) with check (public.has_app_role(public.item_organization(content_item_id), array['media_team','approver','admin']::public.app_role[]));
create policy media_public_ready on public.media_assets for select to anon using (exists(select 1 from public.content_items i where i.id = content_item_id and i.status = 'ready_to_share'));
create policy media_member_all on public.media_assets for all to authenticated using (public.is_organization_member(public.item_organization(content_item_id))) with check (public.has_app_role(public.item_organization(content_item_id), array['media_team','approver','admin']::public.app_role[]));
create policy assignments_member_all on public.assignments for all to authenticated using (public.is_organization_member(public.item_organization(content_item_id))) with check (public.is_organization_member(public.item_organization(content_item_id)));
create policy comments_member_all on public.review_comments for all to authenticated using (public.is_organization_member(public.item_organization(content_item_id))) with check (public.is_organization_member(public.item_organization(content_item_id)) and created_by = (select auth.uid()));
create policy history_member_read on public.status_history for select to authenticated using (public.is_organization_member(coalesce(public.idea_organization(idea_id), public.item_organization(content_item_id))));
create policy history_member_insert on public.status_history for insert to authenticated with check (changed_by = (select auth.uid()) and public.is_organization_member(coalesce(public.idea_organization(idea_id), public.item_organization(content_item_id))));
create policy share_events_public_insert on public.share_events for insert to anon, authenticated with check (exists(select 1 from public.content_items i where i.id = content_item_id and i.status = 'ready_to_share'));
create policy share_events_team_read on public.share_events for select to authenticated using (public.has_app_role(public.item_organization(content_item_id), array['media_team','approver','admin']::public.app_role[]));

grant usage on schema public to anon, authenticated;
grant select on public.platforms, public.content_types to anon, authenticated;
grant select on public.content_items, public.content_platforms, public.media_assets to anon;
grant insert on public.share_events to anon;
grant select, insert, update, delete on public.user_roles, public.campaign_themes, public.ideas, public.idea_platforms, public.content_packages, public.content_items, public.content_platforms, public.media_assets, public.assignments, public.review_comments, public.status_history to authenticated;
grant select, insert on public.share_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;

update storage.buckets set public = true where id = 'campaign-media';
