-- Bridge Media V1 relational model, tenant isolation, and private media storage.
create extension if not exists pgcrypto with schema extensions;

create type public.membership_role as enum ('owner', 'admin', 'member');
create type public.content_status as enum ('idea', 'draft', 'ready', 'scheduled', 'posted');

create table public.organizations (
  id uuid primary key default extensions.gen_random_uuid(),
  name text not null check (length(trim(name)) between 1 and 160),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (length(trim(display_name)) between 1 and 120),
  avatar_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.organization_memberships (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role public.membership_role not null default 'member',
  created_at timestamptz not null default now(),
  primary key (organization_id, profile_id)
);

create table public.campaigns (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 160),
  location text not null check (length(trim(location)) between 1 and 240),
  starts_on date not null,
  ends_on date,
  message text not null check (length(trim(message)) > 0),
  selling_points text[] not null default '{}',
  ai_guidance text not null default '',
  created_by uuid references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campaigns_dates_valid check (ends_on is null or ends_on >= starts_on),
  constraint campaigns_selling_points_valid check (array_position(selling_points, null) is null)
);

create table public.content_items (
  id uuid primary key default extensions.gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  title text not null check (length(trim(title)) between 1 and 200),
  idea text not null check (length(trim(idea)) > 0),
  status public.content_status not null default 'idea',
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.platforms (
  id smallint generated by default as identity primary key,
  key text not null unique check (key ~ '^[a-z0-9_]+$'),
  name text not null unique check (length(trim(name)) > 0),
  sort_order smallint not null unique check (sort_order > 0),
  is_active boolean not null default true
);

create table public.content_platforms (
  id uuid primary key default extensions.gen_random_uuid(),
  content_item_id uuid not null references public.content_items(id) on delete cascade,
  platform_id smallint not null references public.platforms(id) on delete restrict,
  copy text not null default '',
  planned_at timestamptz,
  posted_at timestamptz,
  published_url text check (published_url is null or published_url ~ '^https://'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (content_item_id, platform_id),
  constraint content_platforms_posted_time_valid check (posted_at is null or posted_at >= created_at),
  constraint content_platforms_post_url_valid check (published_url is null or posted_at is not null)
);

create table public.assignments (
  content_item_id uuid primary key references public.content_items(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete restrict,
  assigned_by uuid not null references public.profiles(id) on delete restrict,
  assigned_at timestamptz not null default now()
);

create table public.media_assets (
  id uuid primary key default extensions.gen_random_uuid(),
  content_item_id uuid not null references public.content_items(id) on delete cascade,
  storage_path text not null unique check (storage_path !~ '(^|/)\.\.?(/|$)'),
  file_name text not null check (length(trim(file_name)) between 1 and 255),
  mime_type text not null check (
    mime_type in ('image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/quicktime', 'video/webm')
  ),
  size_bytes bigint not null check (
    size_bytes > 0 and
    ((mime_type like 'image/%' and size_bytes <= 10485760) or
     (mime_type like 'video/%' and size_bytes <= 104857600))
  ),
  alt_text text not null check (length(trim(alt_text)) between 1 and 500),
  uploaded_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table public.results (
  id uuid primary key default extensions.gen_random_uuid(),
  content_platform_id uuid not null references public.content_platforms(id) on delete cascade,
  recorded_at timestamptz not null default now(),
  views bigint not null default 0 check (views >= 0),
  shares bigint not null default 0 check (shares >= 0),
  clicks bigint not null default 0 check (clicks >= 0),
  registrations bigint not null default 0 check (registrations >= 0),
  recorded_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique (content_platform_id, recorded_at)
);

create index organization_memberships_profile_idx on public.organization_memberships(profile_id, organization_id);
create index campaigns_organization_dates_idx on public.campaigns(organization_id, starts_on, ends_on);
create index content_items_campaign_status_idx on public.content_items(campaign_id, status, created_at desc);
create index content_platforms_planned_idx on public.content_platforms(planned_at) where planned_at is not null;
create index content_platforms_posted_idx on public.content_platforms(posted_at desc) where posted_at is not null;
create index assignments_profile_idx on public.assignments(profile_id);
create index media_assets_content_item_idx on public.media_assets(content_item_id);
create index results_variant_recorded_idx on public.results(content_platform_id, recorded_at desc);

create function public.set_updated_at() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger organizations_set_updated_at before update on public.organizations for each row execute function public.set_updated_at();
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger campaigns_set_updated_at before update on public.campaigns for each row execute function public.set_updated_at();
create trigger content_items_set_updated_at before update on public.content_items for each row execute function public.set_updated_at();
create trigger content_platforms_set_updated_at before update on public.content_platforms for each row execute function public.set_updated_at();

create function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
      nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
      'Bridge user'
    )
  );
  return new;
end;
$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create function public.is_organization_member(target_organization_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.organization_memberships m
    where m.organization_id = target_organization_id and m.profile_id = auth.uid()
  );
$$;

create function public.has_organization_role(target_organization_id uuid, allowed_roles public.membership_role[]) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.organization_memberships m
    where m.organization_id = target_organization_id
      and m.profile_id = auth.uid()
      and m.role = any(allowed_roles)
  );
$$;

create function public.campaign_organization(target_campaign_id uuid) returns uuid
language sql stable security definer set search_path = '' as $$
  select organization_id from public.campaigns where id = target_campaign_id
$$;
create function public.content_item_organization(target_content_item_id uuid) returns uuid
language sql stable security definer set search_path = '' as $$
  select c.organization_id from public.content_items i join public.campaigns c on c.id = i.campaign_id where i.id = target_content_item_id
$$;
create function public.content_platform_organization(target_content_platform_id uuid) returns uuid
language sql stable security definer set search_path = '' as $$
  select c.organization_id from public.content_platforms cp
  join public.content_items i on i.id = cp.content_item_id
  join public.campaigns c on c.id = i.campaign_id
  where cp.id = target_content_platform_id
$$;
create function public.profile_is_organization_member(target_profile_id uuid, target_organization_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.organization_memberships where profile_id = target_profile_id and organization_id = target_organization_id)
$$;
create function public.storage_path_organization(object_name text) returns uuid
language plpgsql immutable set search_path = '' as $$
begin
  return split_part(object_name, '/', 1)::uuid;
exception when invalid_text_representation then return null;
end;
$$;

revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.is_organization_member(uuid) from public, anon;
revoke all on function public.has_organization_role(uuid, public.membership_role[]) from public, anon;
revoke all on function public.campaign_organization(uuid) from public, anon;
revoke all on function public.content_item_organization(uuid) from public, anon;
revoke all on function public.content_platform_organization(uuid) from public, anon;
revoke all on function public.profile_is_organization_member(uuid, uuid) from public, anon;
revoke all on function public.storage_path_organization(text) from public, anon;
grant execute on function public.is_organization_member(uuid) to authenticated;
grant execute on function public.has_organization_role(uuid, public.membership_role[]) to authenticated;
grant execute on function public.campaign_organization(uuid) to authenticated;
grant execute on function public.content_item_organization(uuid) to authenticated;
grant execute on function public.content_platform_organization(uuid) to authenticated;
grant execute on function public.profile_is_organization_member(uuid, uuid) to authenticated;
grant execute on function public.storage_path_organization(text) to authenticated;

alter table public.organizations enable row level security;
alter table public.profiles enable row level security;
alter table public.organization_memberships enable row level security;
alter table public.campaigns enable row level security;
alter table public.content_items enable row level security;
alter table public.platforms enable row level security;
alter table public.content_platforms enable row level security;
alter table public.assignments enable row level security;
alter table public.media_assets enable row level security;
alter table public.results enable row level security;

create policy organizations_select_member on public.organizations for select to authenticated using (public.is_organization_member(id));
create policy organizations_update_admin on public.organizations for update to authenticated using (public.has_organization_role(id, array['owner','admin']::public.membership_role[])) with check (public.has_organization_role(id, array['owner','admin']::public.membership_role[]));
create policy profiles_select_colleague on public.profiles for select to authenticated using (id = auth.uid() or exists (select 1 from public.organization_memberships mine join public.organization_memberships theirs using (organization_id) where mine.profile_id = auth.uid() and theirs.profile_id = profiles.id));
create policy profiles_update_self on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy memberships_select_member on public.organization_memberships for select to authenticated using (public.is_organization_member(organization_id));
create policy memberships_insert_admin on public.organization_memberships for insert to authenticated with check (public.has_organization_role(organization_id, array['owner','admin']::public.membership_role[]));
create policy memberships_update_admin on public.organization_memberships for update to authenticated using (public.has_organization_role(organization_id, array['owner','admin']::public.membership_role[])) with check (public.has_organization_role(organization_id, array['owner','admin']::public.membership_role[]));
create policy memberships_delete_admin on public.organization_memberships for delete to authenticated using (public.has_organization_role(organization_id, array['owner','admin']::public.membership_role[]));
create policy campaigns_select_member on public.campaigns for select to authenticated using (public.is_organization_member(organization_id));
create policy campaigns_insert_admin on public.campaigns for insert to authenticated with check (public.has_organization_role(organization_id, array['owner','admin']::public.membership_role[]) and (created_by is null or public.profile_is_organization_member(created_by, organization_id)));
create policy campaigns_update_admin on public.campaigns for update to authenticated using (public.has_organization_role(organization_id, array['owner','admin']::public.membership_role[])) with check (public.has_organization_role(organization_id, array['owner','admin']::public.membership_role[]) and (created_by is null or public.profile_is_organization_member(created_by, organization_id)));
create policy campaigns_delete_admin on public.campaigns for delete to authenticated using (public.has_organization_role(organization_id, array['owner','admin']::public.membership_role[]));
create policy content_items_member_all on public.content_items for all to authenticated using (public.is_organization_member(public.campaign_organization(campaign_id))) with check (public.is_organization_member(public.campaign_organization(campaign_id)) and public.profile_is_organization_member(created_by, public.campaign_organization(campaign_id)));
create policy platforms_authenticated_read on public.platforms for select to authenticated using (true);
create policy content_platforms_member_all on public.content_platforms for all to authenticated using (public.is_organization_member(public.content_item_organization(content_item_id))) with check (public.is_organization_member(public.content_item_organization(content_item_id)));
create policy assignments_member_all on public.assignments for all to authenticated using (public.is_organization_member(public.content_item_organization(content_item_id))) with check (public.is_organization_member(public.content_item_organization(content_item_id)) and public.profile_is_organization_member(profile_id, public.content_item_organization(content_item_id)) and public.profile_is_organization_member(assigned_by, public.content_item_organization(content_item_id)));
create policy media_assets_member_all on public.media_assets for all to authenticated using (public.is_organization_member(public.content_item_organization(content_item_id))) with check (public.is_organization_member(public.content_item_organization(content_item_id)) and public.profile_is_organization_member(uploaded_by, public.content_item_organization(content_item_id)));
create policy results_member_all on public.results for all to authenticated using (public.is_organization_member(public.content_platform_organization(content_platform_id))) with check (public.is_organization_member(public.content_platform_organization(content_platform_id)) and public.profile_is_organization_member(recorded_by, public.content_platform_organization(content_platform_id)));

grant usage on schema public to authenticated;
grant select, update on public.organizations, public.profiles to authenticated;
grant select, insert, update, delete on public.organization_memberships, public.campaigns, public.content_items, public.content_platforms, public.assignments, public.media_assets, public.results to authenticated;
grant select on public.platforms to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke all on all tables in schema public from anon;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('campaign-media', 'campaign-media', false, 104857600, array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/quicktime','video/webm'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy campaign_media_select_member on storage.objects for select to authenticated using (bucket_id = 'campaign-media' and public.is_organization_member(public.storage_path_organization(name)));
create policy campaign_media_insert_member on storage.objects for insert to authenticated with check (bucket_id = 'campaign-media' and public.is_organization_member(public.storage_path_organization(name)) and public.content_item_organization((storage.foldername(name))[2]::uuid) = public.storage_path_organization(name));
create policy campaign_media_update_member on storage.objects for update to authenticated using (bucket_id = 'campaign-media' and public.is_organization_member(public.storage_path_organization(name))) with check (bucket_id = 'campaign-media' and public.is_organization_member(public.storage_path_organization(name)) and public.content_item_organization((storage.foldername(name))[2]::uuid) = public.storage_path_organization(name));
create policy campaign_media_delete_member on storage.objects for delete to authenticated using (bucket_id = 'campaign-media' and public.is_organization_member(public.storage_path_organization(name)));
